### ISSUE TITLE
Error in $this->dispach('/');

### ISSUE THREAD

**Issue by rorteg** [code-x/Xtest#13]
_getRequestRewriteController does not exist in Magento 1.7.0.2. Is not supported for this Magento version?

PHPUnit 4.3.1 by Sebastian Bergmann.

Configuration read from /var/www/magento_1_7_0_2/.modman/Xtest/tests/phpunit.xml.dist

E

Time: 297 ms, Memory: 10.75Mb

There was 1 error:

1) Codex_Demo_Test_Controller_HomepageControllerTest::testHomePageContainsNewProducts
Varien_Exception: Invalid method Codex_Xtest_Model_Core_Controller_Varien_Front::_getRequestRewriteController(Array
(
)
)

/var/www/magento_1_7_0_2/lib/Varien/Object.php:652
/var/www/magento_1_7_0_2/.modman/Xtest/app/code/community/Codex/Xtest/Model/Core/Controller/Varien/Front.php:14
/var/www/magento_1_7_0_2/.modman/Xtest/app/code/community/Codex/Xtest/Model/Core/Controller/Varien/Front.php:14
/var/www/magento_1_7_0_2/.modman/Xtest/app/code/community/Codex/Xtest/Xtest/Unit/Abstract.php:169
/var/www/magento_1_7_0_2/.modman/Xtest/app/code/community/Codex/Xtest/Xtest/Unit/Abstract.php:149
/var/www/magento_1_7_0_2/.modman/xTest.Demo/app/code/local/Codex/Demo/Test/Controller/HomepageControllerTest.php:13
/var/www/magento_1_7_0_2/.modman/Xtest/app/code/community/Codex/Xtest/Xtest/Unit/Abstract.php:94

**Comment by tobi-pb** [comment]
@fschmengler has started some 1.7 compatibility stuff, see https://github.com/schmengler/Xtest/commit/1891e3248cf53d56b4f4a4c72381bdbf5a04ce06

**Comment by rorteg** [comment]
Thank you very much for sharing, we are really enjoying the framework and we are really thinking of adopting it as part of our routines.

**Comment by tobi-pb** [comment]
You are welcome!
