### ISSUE TITLE
Problem when a test fail

### ISSUE THREAD

**Issue by gbinside** [code-x/Xtest#4]
When test are all green, there is no problem.
When I get a red test, instead of printing the problem, I get the following FATAL

PHP Fatal error:  Cannot redeclare class PHPUnit_Framework_Constraint in phar:///<path_to_project>/tests/phpunit.phar/phpunit/Framework/Constraint.php on line 61

Do you have any idea?

Thanks

**Comment by tobi-pb** [comment]
Could you attach an example test thats fails? Please quote your php version, too :-)
