### ISSUE TITLE
Default order fixture throws Exception

### ISSUE THREAD

**Issue by domeglic** [code-x/Xtest#7]
I am testing this on an empty Magento (1.9.1) using a simple test from the examples and it is throwing a Magento core exception: Please specify a shipping method
The example is "Create Order, send order email and check if mail is sent" from http://xtest-mage.com/

**Comment by tobi-pb** [comment]
Hi @domeglic ,

do you imported magento sample data for 1.9 first? Tests are depending on this :)
Did you create a configuration for your test-data? 

We also provide a (hopefully) working demo at https://github.com/code-x/xTest.Demo

Greetings,

Tobi
